#!/bin/bash

if [ "`id -u`" != 0 ]; then
    echo "Run as root, exit"
    exit 1
fi

# detect current directory
BASEDIR=`dirname $0`
BASEDIR=`(cd "$BASEDIR"; pwd)`

PREPARED=${BASEDIR}/prepared
TARGET=${BASEDIR}/image
TARGET_DISTFILES=${TARGET}/usr/portage/distfiles
#SHARED_DISTFILES=/usr/portage/distfiles
SHARED_DISTFILES=${BASEDIR}/../distfiles
INSOURCE_PREPARED=/tmp/prepared

PV_PATH="`which pv 2>/dev/null`"

mount_for_source ()
{
    mount --bind /proc    ${TARGET}/proc
    mount --bind /dev     ${TARGET}/dev
    mount --bind /dev/pts ${TARGET}/dev/pts 
    mount --bind /sys     ${TARGET}/sys
    
    [ -e ${TARGET_DISTFILES} ] || mkdir -p ${TARGET_DISTFILES}
    [ -e ${SHARED_DISTFILES} ] || mkdir -p ${SHARED_DISTFILES}
    
    chmod u=rwX,g=rX,o=rX ${SHARED_DISTFILES}
    mount --bind ${SHARED_DISTFILES} ${TARGET_DISTFILES}
}

umount_for_source ()
{
    umount ${TARGET}/proc
    umount ${TARGET}/sys
    umount ${TARGET}/dev/pts
    umount ${TARGET}/dev    
    umount ${TARGET_DISTFILES}
}
